### ISSUE TITLE
Does the current code support multi GPUs?

### ISSUE THREAD

**Issue by yjcaimeow** [cv-rits/LMSCNet#2]
Dear authors,

Thanks for your great work.

Does the current code support multi GPUs now?

Best
Ying

**Comment by luigui2906** [comment]
Hi,

While we perform all our train and test routines using a single GPU, training with multiple GPUs was considered:

https://github.com/cv-rits/LMSCNet/blob/e6f5a0daf852c2b241170ad4f8a9711c4b3fe526/LMSCNet/train.py#L306-L308

I didn't test the code on multiple GPUs though.
