### ISSUE TITLE
ERROR 'ones needs to be contiguous' 

### ISSUE THREAD

**Issue by Yan-Xia** [cv-rits/LMSCNet#3]
Hi, 

The work is excellent!  But when I  retrain the baseline work 'SSCNet_full' using your codes, I get the 'ones needs to be contiguous' error,  as following:
> Traceback (most recent call last):
  File "LMSCNet/train.py", line 333, in <module>
    main()
  File "LMSCNet/train.py", line 319, in main
    best_record = train(model, optimizer, scheduler, dataset, _cfg, epoch, logger, tbwriter)
  File "LMSCNet/train.py", line 107, in train
    loss['total'].backward()
  File "/opt/conda/lib/python3.7/site-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/__init__.py", line 132, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: ones needs to be contiguous

Have you encountered this issue before?

Thank you in advance.

**Comment by luigui2906** [comment]
Hi, thanks for the interest. I've not encountered this issue.
Could you please provide more details about your cuda installation and setup?

**Comment by luigui2906** [comment]
Hi, I'm closing the issue. Please feel free to reopen if the problem has not been solved.

**Comment by Feynben** [comment]
I encountered the same issue
The details are as below:
Thank you in advance.

Traceback (most recent call last):
  File "LMSCNet/train.py", line 333, in <module>
    main()
  File "LMSCNet/train.py", line 319, in main
    best_record = train(model, optimizer, scheduler, dataset, _cfg, epoch, logger, tbwriter)
  File "LMSCNet/train.py", line 106, in train
    loss['total'].backward()
  File "/cpfs2/user/feiben/envs/lmscnet/lib/python3.7/site-packages/torch/tensor.py", line 198, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/cpfs2/user/feiben/envs/lmscnet/lib/python3.7/site-packages/torch/autograd/__init__.py", line 100, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: ones needs to be contiguous (slow_conv_transpose3d_acc_grad_parameters_cuda at /pytorch/aten/src/ATen/native/cuda/NaiveConvolutionTranspose3d.cu:717)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x46 (0x7fc0fe60a536 in /cpfs2/user/feiben/envs/lmscnet/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: at::native::(anonymous namespace)::slow_conv_transpose3d_acc_grad_parameters_cuda(at::Tensor const&, at::Tensor const&, at::Tensor&, at::Tensor&, at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, int) + 0x26ae (0x7fc100fe94ee in /cpfs2/user/feiben/envs/lmscnet/lib/python3.7/site-packages/torch/lib/libtorch_cuda.so)
frame #2: at::native::slow_conv_transpose3d_backward_cuda(at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, at::Tensor const&, at::Tensor const&, std::array<bool, 3ul>) + 0x32c (0x7fc100feaacc in /cpfs2/user/feiben/envs/lmscnet/lib/python3.7/site-packages/torch/lib/libtorch_cuda.so)
frame #3: <unknown function> + 0xfd689d (0x7fc0ffa3c89d in /cpfs2/user/feiben/envs/lmscnet/lib/python3.7/site-packages/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0xfde5a7 (0x7fc0ffa445a7 in /cpfs2/user/feiben/envs/lmscnet/lib/python3.7/site-packages/torch/lib/libtorch_cuda.so)
frame #5: <unknown function> + 0x2d0e87e (0x7fc13902687e in /cpfs2/user/feiben/envs/lmscnet/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #6: <unknown function> + 0x10c5677 (0x7fc1373dd677 in /cpfs2/user/feiben/envs/lmscnet/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #7: torch::autograd::generated::SlowConvTranspose3DBackward::apply(std::vector<at::Tensor, std::allocator<at::Tensor> >&&) + 0x516 (0x7fc138be5e06 in /cpfs2/user/feiben/envs/lmscnet/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #8: <unknown function> + 0x2d89c05 (0x7fc1390a1c05 in /cpfs2/user/feiben/envs/lmscnet/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #9: torch::autograd::Engine::evaluate_function(std::shared_ptr<torch::autograd::GraphTask>&, torch::autograd::Node*, torch::autograd::InputBuffer&) + 0x16f3 (0x7fc13909ef03 in /cpfs2/user/feiben/envs/lmscnet/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #10: torch::autograd::Engine::thread_main(std::shared_ptr<torch::autograd::GraphTask> const&, bool) + 0x3d2 (0x7fc13909fce2 in /cpfs2/user/feiben/envs/lmscnet/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #11: torch::autograd::Engine::thread_init(int) + 0x39 (0x7fc139098359 in /cpfs2/user/feiben/envs/lmscnet/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #12: torch::autograd::python::PythonEngine::thread_init(int) + 0x38 (0x7fc1457d7828 in /cpfs2/user/feiben/envs/lmscnet/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #13: <unknown function> + 0xbd6df (0x7fc1468a76df in /usr/lib/x86_64-linux-gnu/libstdc++.so.6)
frame #14: <unknown function> + 0x76db (0x7fc1485cd6db in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #15: clone + 0x3f (0x7fc1482f671f in /lib/x86_64-linux-gnu/libc.so.6)
