### ISSUE TITLE
List Index Out of Range Error during Training - Why is it occurring at Iteration [300/480]?

### ISSUE THREAD

**Issue by jmwang0117** [cv-rits/LMSCNet#7]
Hi,

First and foremost, I want to express my sincere gratitude for your hard work and the valuable code you have provided. I have encountered an issue during training and I am seeking your expertise to resolve it. Specifically, I am facing a "List Index Out of Range" error at Iteration [300/480].

I have examined the code and identified that the error is related to accessing `self.filepaths['3D_INVALID'][scale][idx]` and `self.filepaths['3D_LABEL'][scale][idx]`. Prior to this iteration, I have successfully loaded and trained the model without any issues.

the code trying to call the get_label_at_scale function with an index value of idx=3834. However, upon inspecting the code, I found that there seems to be an issue when accessing self.filepaths['3D_INVALID'][scale][idx] and self.filepaths['3D_LABEL'][scale][idx].

To investigate further, I printed the lengths of the lists self.filepaths['3D_INVALID'][scale] and self.filepaths['3D_LABEL'][scale] and discovered that both lengths are same( idx=3834). This results in an index out of range error.

I was wondering if you could help me understand why this situation is occurring. In my understanding, the index should be within the range of the list.How to solve this problem?

![image](https://github.com/astra-vision/LMSCNet/assets/51500826/247d846d-6a78-4e17-b04e-3b65eb471dda)

**Comment by jmwang0117** [comment]
achieve

**Comment by fengyxz** [comment]
hello~ I wonder how did you solve it? I encountered the  same question. THX！！！
