### ISSUE TITLE
Strange voxel in ground truth

### ISSUE THREAD

**Issue by zhyzhyzhy123** [cv-rits/LMSCNet#8]
Hi Luis, thanks for your great work. 

I found something strange in the visulization result, in paper Figure 9, right side, there is a long voxel block categorized as a car, which I have circled in red below.
![企业微信截图_17089359239890](https://github.com/astra-vision/LMSCNet/assets/31156721/c5724c09-7131-4da0-a7b0-8621994e95e3)
And which I found it in my visulization result, which use the script provided in [issue]( #1 ). Do you know what is it?

**Comment by luigui2906** [comment]
Hi, thank you for your interest.

This comes from the dynamic objects (vehicles in this case) captured at each individual scan and accumulated for the semi-dense GT creation which results on these traces.

**Comment by zhyzhyzhy123** [comment]
Thanks for your reply, so is this the combination from five frames of  scan? Will these things influence the result of the model?

**Comment by luigui2906** [comment]
It is more than 5 frames that are accumulated for the ground-truth, you can check the details on the official dataset site (http://www.semantic-kitti.org/dataset.html#overview) and their provided tool (https://github.com/jbehley/voxelizer).

For the results of the model, we observed that all vehicles are predicted without traces which could be explained by the larger amount of static vehicles on the dataset, compared to dynamic ones. This is explained on the Section B of the supplementary :

>  Even though the ground-truth in Se manticKITTI accumulates scans of dynamic objects as seen in rows 3-4, our network reconstructs the vehicles correctly. This can be explained by the abundance of parked vehi cles in the dataset

More details can also be found on our survey (https://arxiv.org/abs/2103.07466). 
Good luck ;)
